import {StyleSheet} from 'react-native';
import {BorderStyles, Sizes, Shadow} from '../../assets/styles';
import {deviceInfo} from '../../assets/deviceInfo';

const styles = (theme) => {
  return StyleSheet.create({
    disabledLink: {
      opacity: 0.5,
    },
    spamTitle: {
      alignSelf: 'center',
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      fontSize: Sizes.size20,
      marginBottom: Sizes.size11,
      fontWeight: deviceInfo.ios ? '500' : 'bold',
    },
    spamRbsHeetContainer: {
      paddingHorizontal: Sizes.size10,
      paddingBottom: Sizes.size10,
    },
    greyText: {
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      fontSize: Sizes.size14,
      alignSelf: 'center',
      fontWeight: deviceInfo.ios ? '500' : 'bold',
    },
    removeIconContainer: {
      flexDirection: 'row',
      padding: Sizes.size10,
      borderTopColor: theme?.color?.BORDER_THIN_COLOR,
      borderTopWidth: 0.5,
    },
    locationButton: {
      position: 'absolute',
      zIndex: 100,
      width: Sizes.size42,
      height: Sizes.size42,
      right: Sizes.size7,
      bottom: Sizes.size12,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: Sizes.size12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    container: {
      flex: 1,
    },
    mapContainer: {
      flex: 1,
    },
    iconsContent: {
      alignSelf: 'center',
      alignItems: 'flex-end',
      margin: Sizes.size5,
      backgroundColor: '#F3F3F4',
      padding: Sizes.size10,
      borderRadius: Sizes.size10,
    },
    searchInput: {
      marginTop: Sizes.size10,
      position: 'absolute',
      justifyContent: 'space-between',
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: Sizes.size10,
      paddingHorizontal: Sizes.size10,
      width: '95%',
      height: Sizes.size46,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: Sizes.size20,
      ...Shadow,
    },
    typeIcons: {
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      height: Sizes.size30,
      alignSelf: 'center',
      margin: Sizes.size3,
      flexDirection: 'row',
      ...Shadow,
    },
    eventType: {
      alignSelf: 'center',
      paddingHorizontal: Sizes.size7,
      paddingVertical: Sizes.size2,
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      fontSize: Sizes.size12,
    },
    userLocationButton: {
      position: 'absolute',
      zIndex: 100,
      width: Sizes.size42,
      height: Sizes.size42,
      right: Sizes.size5,
      bottom: Sizes.size100,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: Sizes.size12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mapZoomButtonsContainer: {
      position: 'absolute',
      zIndex: 100,
      width: Sizes.size40,
      height: Sizes.size80,
      right: Sizes.size5,
      top: deviceInfo.deviceHeight / 2 - 75,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: 10,
    },
    zoomButton: {
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 10,
      flex: 0.5,
    },
    headerContainer: {
      flexDirection: 'row',
      marginTop: Sizes.size2,
      paddingVertical: Sizes.size20,
      paddingHorizontal: Sizes.size10,
    },
    iconsContainer: {
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      width: Sizes.size45,
      height: Sizes.size45,
      marginLeft: Sizes.size3,
      borderRadius: BorderStyles.radius.circle,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    touchable: {
      backgroundColor: theme?.PRIMARY_TEXT_COLOR_LIGHT,
      borderRadius: BorderStyles.radius.circle,
      position: 'absolute',
      width: Sizes.size7,
      top: -Sizes.size3,
      right: -Sizes.size4,
      height: Sizes.size7,
      flexDirection: 'row',
      alignSelf: 'flex-end',
    },
    cardTitle: {
      color: theme.color.INPUT_DEFAULT_COLOR,
      fontSize: Sizes.size15,
      fontWeight: deviceInfo.ios ? '500' : 'bold',
      lineHeight: 18,
    },
    cardDescription: {
      width: Sizes.size250,
      color: theme.color.INPUT_DEFAULT_COLOR,
      fontSize: Sizes.size12,
      fontWeight: '400',
      lineHeight: 14,
    },
    cardTitleContainer: {
      position: 'absolute',
      bottom: 0,
      zIndex: 999,
      width: '100%',
      backgroundColor: 'rgba(255, 255, 255,0.9)',
      borderRadius: Sizes.size20,
      height: Sizes.size90,
      paddingHorizontal: Sizes.size15,
    },
    contentFeedBack: {
      borderRadius: Sizes.size20,
      backgroundColor: '#FFFFFF',
      marginVertical: 5,
      width: '90%',
      minWidth: Sizes.size355,
      minHeight: Sizes.size400,
      borderWidth: Sizes.size1,
      borderColor: '#D8D8EC',
      ...Shadow,
    },
    flexCenter: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    nameContainer: {
      fontSize: Sizes.size14,
      marginLeft: Sizes.size4,
      width: '50%',
    },
    topbarContainer: {
      marginLeft: 10,
      alignItems: 'flex-start',
      width: '80%',
    },
    backgroundImage: {
      flex: 1,
      borderBottomRightRadius: Sizes.size20,
      borderBottomLeftRadius: Sizes.size20,
    },
    flex: {
      flex: 1,
    },
  });
};

export {styles};
