require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MyTestApp' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  use_react_native!(
      :path => config["reactNativePath"],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :hermes_enabled => true
  )
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RNTextGradientView', :path => '../node_modules/react-native-text-gradient'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'Firebase/Crashlytics'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'


  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'MyTestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
   flipper_post_install(installer)
     installer.pods_project.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
     end
  end
end

target 'MyTestApp-tvOS' do
  # Pods for MyTestApp-tvOS

  target 'MyTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
