import {Dimensions, StyleSheet} from 'react-native';
import {deviceInfo} from '../../assets/deviceInfo';
import {
  BorderStyles,
  fullScreen,
  PaddingMargin,
  Shadow,
  Sizes,
} from '../../assets/styles';

const styles = (theme) => {
  return StyleSheet.create({
    disabledLink: {
      opacity: 0.5,
    },
    removeIconContainer: {
      flexDirection: 'row',
      padding: Sizes.size10,
      borderTopColor: theme?.color?.BORDER_THIN_COLOR,
      borderTopWidth: 0.5,
    },
    spamRbsHeetContainer: {
      paddingHorizontal: Sizes.size10,
      paddingBottom: Sizes.size10,
    },
    spamTitle: {
      alignSelf: 'center',
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      fontSize: Sizes.size20,
      marginBottom: Sizes.size11,
      fontWeight: deviceInfo.ios ? '500' : 'bold',
    },
    container: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: Sizes.size15,
      flex: 1,
    },
    eventName: {
      fontSize: Sizes.size18,
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      paddingHorizontal: PaddingMargin.screenPaddingHorizontal,
    },
    iconContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    greyText: {
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      fontSize: Sizes.size14,
      alignSelf: 'center',
      fontWeight: deviceInfo.ios ? '500' : 'bold',
    },
    locationButton: {
      position: 'absolute',
      zIndex: 100,
      width: Sizes.size34,
      height: Sizes.size34,
      right: Sizes.size8,
      bottom: Sizes.size19,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: Sizes.size12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mapContainer: {
      flex: 1,
    },
    iconsContent: {
      alignSelf: 'center',
      alignItems: 'flex-end',
      margin: Sizes.size5,
      backgroundColor: '#F3F3F4',
      padding: Sizes.size10,
      borderRadius: Sizes.size10,
    },
    searchInput: {
      marginTop: Sizes.size10,
      position: 'absolute',
      justifyContent: 'space-between',
      flexDirection: 'row',
      marginHorizontal: Sizes.size10,
      paddingHorizontal: Sizes.size10,
      alignItems: 'center',
      width: '95%',
      height: Sizes.size46,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: BorderStyles.radius.s,
      ...Shadow,
    },
    typeIcons: {
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      height: Sizes.size30,
      alignSelf: 'center',
      margin: Sizes.size3,
      flexDirection: 'row',
      ...Shadow,
    },
    eventType: {
      alignSelf: 'center',
      paddingHorizontal: Sizes.size7,
      paddingVertical: Sizes.size2,
      color: theme?.color?.PRIMARY_COLOR_LIGHT,
      fontSize: Sizes.size12,
    },
    userLocationButton: {
      position: 'absolute',
      zIndex: 100,
      width: Sizes.size42,
      height: Sizes.size42,
      right: Sizes.size5,
      bottom: Sizes.size100,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: Sizes.size12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mapZoomButtonsContainer: {
      position: 'absolute',
      zIndex: 100,
      width: Sizes.size40,
      height: Sizes.size80,
      right: Sizes.size5,
      top: deviceInfo.deviceHeight / 2 - 75,
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      borderRadius: 10,
    },
    zoomButton: {
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 10,
      flex: 0.5,
    },
    headerContainer: {
      flexDirection: 'row',
      marginTop: Sizes.size2,
      paddingVertical: Sizes.size20,
      paddingHorizontal: Sizes.size10,
    },
    iconsContainer: {
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      width: Sizes.size45,
      height: Sizes.size45,
      marginLeft: Sizes.size3,
      borderRadius: BorderStyles.radius.circle,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    touchable: {
      backgroundColor: theme?.PRIMARY_TEXT_COLOR_LIGHT,
      borderRadius: BorderStyles.radius.circle,
      position: 'absolute',
      width: Sizes.size7,
      top: -Sizes.size3,
      right: -Sizes.size4,
      height: Sizes.size7,
      flexDirection: 'row',
      alignSelf: 'flex-end',
    },
    video: {
      width: Dimensions.get('window').width,
      height: Dimensions.get('window').width * (9 / 16),
      backgroundColor: theme?.PRIMARY_BACKGROUND_COLOR,
      position: 'absolute',
      top: '50%',
      left: '50%',
    },
    videoBlock: {
      flex: 1,
      backgroundColor: 'rgba(225,225,225,0.5)',
      position: 'absolute',
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      zIndex: 999,
    },
    videoControl: {
      alignSelf: 'flex-end',
      marginHorizontal: 22,
      marginVertical: 5,
      width: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 90,
      backgroundColor: theme?.SECONDARY_BACKGROUND_COLOR_LIGHT,
    },
    closeVideo: {
      padding: Sizes.size5,
    },
    closeVideoContainer: {
      width: '100%',
      marginHorizontal: 'auto',
      alignItems: 'flex-end',
      justifyContent: 'center',
    },

    videoView: {
      marginTop: 10,
      alignItems: 'center',
      width: 80,
      height: 80,
      justifyContent: 'center',
      backgroundColor: theme?.SECONDARY_BACKGROUND_COLOR_LIGHT,
      borderRadius: 22,
    },
    fullVideo: {
      width: '100%',
      backgroundColor: theme?.SECONDARY_BACKGROUND_COLOR_LIGHT,
      height: '100%',
      borderRadius: 22,
    },
    playButton: {
      width: 80,
      height: 80,
      borderRadius: 22,
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventItemHeader: {
      marginLeft: 10,
      alignItems: 'flex-start',
      width: '50%',
    },
    eventItemUsername: {
      fontSize: Sizes.size14,
      marginLeft: Sizes.size4,
      fontWeight: '400',
    },
    usersDataContainer: {
      flex: 1,
      paddingHorizontal: 12,
      // marginVertical: Sizes.size15,
    },
    boldDesc: {},
    sendButtonGradient: {
      borderRadius: Sizes.size10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sendButton: {
      width: Sizes.size148,
      paddingVertical: Sizes.size6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendButtonText: {
      color: 'white',
      fontWeight: deviceInfo.ios ? '600' : 'bold',
      fontSize: Sizes.size12,
      lineHeight: 15,
    },
    leftEventContainer: {
      borderRadius: Sizes.size10,
      width: Sizes.size148,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: Sizes.size6,
      backgroundColor: '#F3F3F3',
    },
    leftEventText: {
      color: '#818195',
      fontWeight: deviceInfo.ios ? '600' : 'bold',
      fontSize: Sizes.size12,
      lineHeight: 15,
    },
    deleteRequestContainer: {
      borderRadius: Sizes.size10,
      width: Sizes.size148,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: Sizes.size6,
      backgroundColor: '#F3F3F3',
    },
    deleteRequestText: {
      color: '#818195',
      fontWeight: deviceInfo.ios ? '600' : 'bold',
      fontSize: Sizes.size12,
      lineHeight: 15,
    },
    moreContainer: {
      transform: [{rotate: '90deg'}],
      marginLeft: 'auto',
      padding: Sizes.size2,
    },
    eventDetailContainer: {
      borderRadius: Sizes.size20,
      backgroundColor: '#FFFFFF',
      marginVertical: 5,
    },
    eventDetail: {
      padding: Sizes.size13,
      flexDirection: 'row',
    },
    eventDetailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingRight: Sizes.size7,
    },
    customSliderContainer: {
      height: Sizes.size355,
    },
    modalContainer: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: 'rgba(0,0,0,0.4)',
      flex: deviceInfo.ios ? 1 : null,
      width: '100%',
      height: deviceInfo.android ? fullScreen.height + Sizes.size30 : null,
      justifyContent: 'center',
    },
    modalContent: {
      width: '90%',
      alignSelf: 'center',
      borderRadius: Sizes.size20,
      alignItems: 'center',
      justifyContent: 'center',
      height: '50%',
    },
  });
};
export {styles};
